
package vista;

import beans.Usuario;
import java.awt.event.ActionListener;

public class VistaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaPantallaPrincipal
     */
    public VistaUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void mostrarVistaUsuario(Usuario usuario){
        this.campoNombre.setText(usuario.getUsuario());
        this.campoEdad.setText(usuario.getEdad() + " años");
        this.campoOcupacion.setText(usuario.getOficio());
        this.setVisible(true);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoEdad = new javax.swing.JLabel();
        campoOcupacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 320, 130, 30);

        campoNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(campoNombre);
        campoNombre.setBounds(200, 320, 350, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EDAD:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 380, 130, 30);

        campoEdad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoEdad.setForeground(new java.awt.Color(255, 255, 255));
        campoEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(campoEdad);
        campoEdad.setBounds(200, 380, 350, 30);

        campoOcupacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        campoOcupacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(campoOcupacion);
        campoOcupacion.setBounds(200, 440, 350, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/icono_usuario.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 20, 210, 270);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("OCUPACION:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 440, 130, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/fondo.png"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(600, 600));
        fondo.setMinimumSize(new java.awt.Dimension(600, 600));
        fondo.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 600, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel campoEdad;
    public javax.swing.JLabel campoNombre;
    public javax.swing.JLabel campoOcupacion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
